Fix syntax error

diff --git a/.github/workflows/conda_build_and_publish.yml b/.github/workflows/conda_build_and_publish.yml
--- a/.github/workflows/conda_build_and_publish.yml
+++ b/.github/workflows/conda_build_and_publish.yml
@@ -28,52 +28,52 @@ jobs:
       with:
         name: test-gh-actions-package
         path: recipe/noarch/hello*
-    docs_build:
-      runs-on: ubuntu-latest
-      steps:
-      - name: Download artifact of the conda package.
-        uses: actions/download-artifact@v2
-        with:
-          name: 'test-gh-actions-build.tar.bz2'
-          path: 'conda_package'
-      - uses: conda-incubator/setup-miniconda@v2
-        with:
-          python-version: 3.7
-          activate-environment: test-gh-actions-build
-      - uses: cascode-labs/build-sphinx-action@v0.1.0
-        with:
-          DOCS_PATH: 'test-gh-actions/docs/'
-          CONDA_BUILD_ENV_FILEPATH: 'test-gh-actions/docs/docs_environment.yml'
-          ARTIFACT_NAME: 'DocumentationHTML'
-          PACKAGE_FOLDER_PATH: 'conda_package'
-          PACKAGE_NAME: 'test-gh-actions-build.tar.bz2'
-    publish:
-      runs-on: ubuntu-latest
-      needs: build
-      if: github.ref == 'refs/heads/main'
-      steps:
-      - name: Download artifact of the html output.
-        uses: actions/download-artifact@v2
-        with:
-          name: DocumentationHTML
-          path: test-gh-actions/docs/build/nightly
-      - name: Commit documentation changes
-        run: |
-          git clone https://github.com/lauramurgatroyd/test-gh-actions.git --branch gh-pages --single-branch gh-pages
-          cp -r test-gh-actions/docs/build/* gh-pages/
-          cd gh-pages
-          touch .nojekyll
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          git add .
-          git commit -m "Update documentation" -a || true
-          # The above command will fail if no changes were present, so we ignore
-          # that.
-      - name: Push changes
-        uses: ad-m/github-push-action@main
-        with:
-          branch: gh-pages
-          directory: gh-pages
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+  docs_build:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Download artifact of the conda package.
+      uses: actions/download-artifact@v2
+      with:
+        name: 'test-gh-actions-build.tar.bz2'
+        path: 'conda_package'
+    - uses: conda-incubator/setup-miniconda@v2
+      with:
+        python-version: 3.7
+        activate-environment: test-gh-actions-build
+    - uses: cascode-labs/build-sphinx-action@v0.1.0
+      with:
+        DOCS_PATH: 'test-gh-actions/docs/'
+        CONDA_BUILD_ENV_FILEPATH: 'test-gh-actions/docs/docs_environment.yml'
+        ARTIFACT_NAME: 'DocumentationHTML'
+        PACKAGE_FOLDER_PATH: 'conda_package'
+        PACKAGE_NAME: 'test-gh-actions-build.tar.bz2'
+  publish:
+    runs-on: ubuntu-latest
+    needs: build
+    if: github.ref == 'refs/heads/main'
+    steps:
+    - name: Download artifact of the html output.
+      uses: actions/download-artifact@v2
+      with:
+        name: DocumentationHTML
+        path: test-gh-actions/docs/build/nightly
+    - name: Commit documentation changes
+      run: |
+        git clone https://github.com/lauramurgatroyd/test-gh-actions.git --branch gh-pages --single-branch gh-pages
+        cp -r test-gh-actions/docs/build/* gh-pages/
+        cd gh-pages
+        touch .nojekyll
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # that.
+    - name: Push changes
+      uses: ad-m/github-push-action@main
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
 
 
